version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: post_db

  backend:
    image: flashhhhh/simple_app_backend
    ports:
      - "8000:8000"
    environment:
      PG_HOST: postgres
    depends_on:
      - postgres

  frontend:
    image: flashhhhh/simple_app_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000